spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #数据源基本配置
    username: sell
    password:
    url: jdbc:mysql://106.54.200.93:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    open-in-view: false
#项目访问路径名
server:
  servlet:
    context-path: /sell
