spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #数据源基本配置
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.18:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    open-in-view: false
  jackson:
     time-zone: GMT+8
     date-format: yyyy-MM-dd HH:mm:ss
     #配置返回属性不为空
     default-property-inclusion: non_null
     #返回时间戳（一串数字）
     #serialization:
       #write-dates-as-timestamps: true
#项目访问路径名
server:
  servlet:
    context-path: /sell
  #port: 80